app:
  name: counterfeitnote

server:
  port: 80

spring:
  profiles.active: dev

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://10.57.11.25:3306/Wizard
    username: CDC_Joe_rw
    password: Joe@#$789
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    initialize: true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

inquiry:
  check:
    dalay:
      minutes: 1

logging:
  file: logs/server.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} : %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} : %msg%n"
  level:
    root: ERROR
    org.springframework: WARN
    org.hibernate: WARN
    com.esfb.counterfeitnote: DEBUG

debug: true

locale:
  langcode: en_us

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://10.57.11.25:3306/Wizard
    username: app
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    platform: oracle
    initialize: false
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
      connectionTestQuery: select now()
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
  cache:
    ehcache:
      config: classpath:ehcache.xml
  thymeleaf:
    cache: true

logging:
  file: logs/server.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} : %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} : %msg%n"
    MaxFileSize: 1MB
  level:
    root: ERROR
    org.springframework: ERROR
    org.hibernate: ERROR
    com.counterfeitnotes: ERROR

---